name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ставим Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Кэшируем pip-зависимости (ускоряет повторные сборки)
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Устанавливаем зависимости проекта + инструменты безопасности
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r app/requirements.txt
          pip install pytest bandit semgrep pip-audit flake8

      # 5. Запуск unit-тестов (pytest)
      - name: Run unit tests
        run: pytest app/tests

      # 6. Анализ кода на уязвимости (Bandit)
      - name: Static analysis (Bandit)
        run: bandit -r app

      # 7. Дополнительный поиск ошибок и багов (Semgrep)
      - name: Static analysis (Semgrep)
        run: semgrep --config=auto app || true

      # 8. Проверка зависимостей на уязвимости (pip-audit)
      - name: Dependency scan (pip-audit)
        run: pip-audit || true

      # 9. Проверка качества кода (flake8)
      - name: Lint with flake8
        run: flake8 app

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # 10. Забираем код для сборки образа
      - name: Checkout repository
        uses: actions/checkout@v3

      # 11. Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t secure-pipeline-demo .

      # 12. Сканирование Docker-образа на уязвимости (Trivy)
      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "secure-pipeline-demo"
          format: "table"

      # 13. Логин в GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 14. Публикация Docker-образа в GHCR
      - name: Push Docker image
        run: |
          docker tag secure-pipeline-demo ghcr.io/${{ github.repository }}/secure-pipeline-demo:latest
          docker push ghcr.io/${{ github.repository }}/secure-pipeline-demo:latest
